apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
spec:
  selector:
    matchLabels:
      app: flaskdemo
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - name: flaskdemo
        image: webtechnelson/ci-test-image:5
        ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flaskdemo-service
spec:
  selector:
    app: flaskdemo
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
